version: '3.1'

services:
  mongo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-mongo
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - ./docker/mongo/data:/data/db