FROM alpine:latest

RUN apk add --update --no-cache bash mongodb && \
  rm -rf ${RM_DIRS} /usr/share/man /tmp/* /var/cache/apk/* \
  /.gnupg /usr/bin/mongoperf

RUN mkdir -p /data/db

EXPOSE 27017 28017

CMD ["/usr/bin/mongod"]